In [1]:
import pandas as pd
import numpy as np
import os
import string

In [8]:
list_folder = [57, 58, 59, 60, 61,     62, 63, 64, 65, 66]
# start_row
list_start_row = [9, 9, 9, 9, 8,    8, 8, 8, 8, 8]
list_t0 = []
list_t0.append((['A', 'D', 'D', 'C', 'C',    'C', 'C', 'E', 'E', 'D'], 'วิทยาเขต'))
list_t0.append((['B', 'E', 'E', 'D', 'D',    'D', 'D', 'F', 'F', 'E'], 'คณะ'))
list_t0.append((['C', 'F', 'F', None, None, None, None, None, None, None], 'ภาค'))
list_t0.append((['D', 'G', 'G', 'E', 'E',    'E', 'E', 'G', 'G', 'F'], 'สาขา'))

list_t1 = []
list_t1.append((['E', 'H', 'H', 'F', 'F',    'F', 'F', 'H', 'H', 'G'], 'ผู้สำเร็จการศึกษา'))
list_t1.append((['F', 'I', 'I', 'G', 'G',    'G', 'G', 'I', 'I', 'H'], 'ผู้บันทึกข้อมูล'))
list_t1.append((['H', 'K', 'K', 'I', 'I',    'I', 'I', 'L', 'K', 'J'], 'มีงานทำเดิม'))
list_t1.append((['M', 'P', 'P', 'N', 'N',    'N', 'N', 'P', 'O', 'N'], 'ขอบเขตสำรวจ'))

list_t2 = []
list_t2.append((['E', 'H', 'H', 'F', 'F',    'F', 'F', 'H', 'H', 'G'], 'ทำงาน'))
list_t2.append((['F', 'I', 'I', 'G', 'G',    'G', 'G', 'I', 'I', 'H'], 'รัฐ'))
list_t2.append((['H', 'K', 'K', 'I', 'I',    'I', 'I', 'K', 'K', 'J'], 'รัฐวิสาหกิจ'))
list_t2.append((['J', 'M', 'M', 'K', 'K',    'K', 'K', 'M', 'M', 'L'], 'เอกชน'))
list_t2.append((['L', 'O', 'O', 'M', 'M',    'M', 'M', 'O', 'O', 'N'], 'ธุรกิจส่วนตัว/อิสระ'))
list_t2.append(([None, 'Q', 'Q', 'O', 'O',   'O', 'O', None, None, 'P'], 'องค์การระหว่างประเทศ'))
list_t2.append((['N', 'S', 'S', 'Q', None,   'Q', None, 'Q', 'Q', 'R'], 'ทำงานที่อื่นๆ'))
list_t2.append((['P', 'U', 'U', 'S', 'Q',    'S', 'Q', 'S', 'S', 'T'], 'งานตรงสาขา'))
list_t2.append((['R', None, None, None, 'S',  'U', 'S', 'U', 'U', 'V'], 'งานไม่ตรงสาขา'))
list_t2.append((['T', None, None, None, 'U',  None, None, None, None, None], 'งานไม่ระบุสาขา'))
list_t2.append((['V', 'W', 'W', 'U', 'W',    'W', 'T', 'W', 'W', 'X'], 'รายได้เฉลี่ย'))

list_t3 = []
list_t3.append((['E', 'H', 'H', 'F', 'F',    'F', 'F', 'H', 'H', 'G'], 'ไม่ทำงาน'))
list_t3.append((['F', 'Q', 'K', 'O', 'K',    'O', 'I', 'K', 'K', 'J'], 'รอคำตอบ'))
list_t3.append((['H', 'S', 'M', 'Q', 'M',    'Q', 'K', 'M', 'M', 'L'], 'หางานไม่ได้'))
list_t3.append((['J', 'I', 'S', 'G', 'G',    'G', 'S', 'U', 'U', 'T'], 'ศึกษาต่อ'))
list_t3.append((['L', 'K', 'I', 'I', 'I',    'I', 'G', 'I', 'I', 'H'], 'ไม่ประสงค์ทำงาน'))
list_t3.append((['N', 'M', 'O', 'K', 'Q',    'K', 'O', 'Q', 'Q', 'P'], 'บวช'))
list_t3.append((['P', 'O', 'Q', 'M', 'S',    'M', 'Q', 'S', 'S', 'R'], 'เกณฑ์ทหาร'))
list_t3.append(([None, None, None, None, 'O','S', 'M', 'O', 'O', 'N'], 'ต้องการทำงานอิสระ'))
list_t3.append((['R', 'U', 'U', 'U', 'U',    'U', 'U', 'W', 'W', 'V'], 'ไม่ทำงาน สาเหตุอื่นๆ'))

idx = 9
start_row = list_start_row[idx]
pattern_T0 = list( map(lambda x: (x[1], x[0][idx]), list_t0) )
pattern_T1 = pattern_T0 + list( map(lambda x: (x[1], x[0][idx]), list_t1) )
print('pattern_T1')
pattern_T1

pattern_T1

[('วิทยาเขต', 'D'),
 ('คณะ', 'E'),
 ('ภาค', None),
 ('สาขา', 'F'),
 ('ผู้สำเร็จการศึกษา', 'G'),
 ('ผู้บันทึกข้อมูล', 'H'),
 ('มีงานทำเดิม', 'J'),
 ('ขอบเขตสำรวจ', 'N')]

In [3]:
all_df = {}
T123 = {}

result = None
for idx, folder in enumerate(list_folder):
    result = None
    start_row = list_start_row[idx]
    pattern_T0 = list( map(lambda x: (x[1], x[0][idx]), list_t0) )
    pattern_T1 = pattern_T0 + list( map(lambda x: (x[1], x[0][idx]), list_t1) )
    pattern_T2 = pattern_T0 + list( map(lambda x: (x[1], x[0][idx]), list_t2) )
    pattern_T3 = pattern_T0 + list( map(lambda x: (x[1], x[0][idx]), list_t3) )


    folder_path = '../data/' + str(folder)
    excel_files = [f for f in os.listdir(folder_path) if f.endswith(('.xlsx', '.xls'))]

    T123 = {}
    for file in excel_files:
        table = ''
        if 'T1' in file:
            table = 'T1'
            pattern = pattern_T1
        elif 'T2' in file:
            table = 'T2'
            pattern = pattern_T2
        elif 'T3' in file:
            table = 'T3'
            pattern = pattern_T3
        elif 'T4' in file:
            continue
        elif 'T5' in file:
            continue
        elif 'T6' in file:
            continue

        file_path = os.path.join(folder_path, file)

        df = pd.read_excel(file_path, header=None)
        df.columns = list(string.ascii_uppercase[:df.shape[1]])

        df = df[start_row-1:]

        patt = list( filter(lambda x: x[1] != None, pattern) )
        df = df[list(map(lambda x: x[1], patt))]
        df.columns = list(map(lambda x: x[0], patt))
        df['keep'] = np.select([df["สาขา"].isna()], [0], 1)
        df.ffill(inplace=True)
        df = df[df["keep"] == 1]
        df.drop(columns=['keep'], inplace=True)
        
        ex_cols = list(df.columns)
        df['ปี'] = folder
        df = df[['ปี'] + ex_cols]
        # print(df)
        
        patt_none = list( filter(lambda x: x[1] == None, pattern) )
        patt_none = list( map(lambda x: x[0], patt_none) )
        df = df.assign(**{col: None for col in patt_none})
        T123[table] = df

        if table == 'T3':
            result = T123['T1'].merge(
                T123['T2'],
                on=["ปี", "วิทยาเขต", "คณะ", "ภาค", "สาขา"],
                how="left"
            )
            result = result.merge(
                T123['T3'],
                on=["ปี", "วิทยาเขต", "คณะ", "ภาค", "สาขา"],
                how="left"
            )
            all_df[folder] = result
    # break

C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)
C:\Users\noppawat.c\AppData\Local\Temp\ipykernel_71936\2022786907.py:47: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(inplace=True)

In [4]:
# Concatenate vertically
all_result = pd.concat(all_df.values(), ignore_index=True)

In [5]:
all_result.to_excel('all_result ป.ตรี.xlsx')

In [6]:
all_result

,ปี,วิทยาเขต,คณะ,ภาค,สาขา,ผู้สำเร็จการศึกษา,ผู้บันทึกข้อมูล,มีงานทำเดิม,ขอบเขตสำรวจ,ทำงาน,...,องค์การระหว่างประเทศ,ไม่ทำงาน,รอคำตอบ,หางานไม่ได้,ศึกษาต่อ,ไม่ประสงค์ทำงาน,บวช,เกณฑ์ทหาร,ไม่ทำงาน สาเหตุอื่นๆ,ต้องการทำงานอิสระ
0,57,1. บางเขน,เกษตร,ภาคปกติ,วิทยาศาสตรบัณฑิต (การจัดการศัตรูพืช),3,3,0,3,2,...,None,1,1,0,0,0,0,0,0,None
1,57,1. บางเขน,เกษตร,ภาคปกติ,วิทยาศาสตรบัณฑิต (การจัดการศัตรูพืชและสัตว์),24,23,0,15,9,...,None,14,6,0,6,1,0,1,0,None
2,57,1. บางเขน,เกษตร,ภาคปกติ,วิทยาศาสตรบัณฑิต (คหกรรมศาสตร์),36,36,0,27,17,...,None,19,3,6,3,6,0,0,1,None
3,57,1. บางเขน,เกษตร,ภาคปกติ,วิทยาศาสตรบัณฑิต (เคมีการเกษตร),32,32,0,22,16,...,None,16,3,2,5,5,0,0,1,None
4,57,1. บางเขน,เกษตร,ภาคปกติ,วิทยาศาสตรบัณฑิต (วิทยาศาสตร์เกษตร),169,163,0,97,66,...,None,97,20,10,34,27,1,4,1,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1872,66,4 เฉลิมพระเกียรติ จังหวัดสกลนคร,ศิลปศาสตร์และวิทยาการจัดการ,None,รัฐประศาสนศาสตรบัณฑิต,57,57,-,53,25,...,-,32,7,3,1,8,-,3,2,8
1873,66,4 เฉลิมพระเกียรติ จังหวัดสกลนคร,ศิลปศาสตร์และวิทยาการจัดการ,None,ศิลปศาสตรบัณฑิต สาขาวิชาภาษาอังกฤษ,113,108,-,103,44,...,2,64,18,4,2,27,-,3,3,7
1874,66,4 เฉลิมพระเกียรติ จังหวัดสกลนคร,สาธารณสุขศาสตร์,None,วิทยาศาสตรบัณฑิต สาขาวิชาอนามัยสิ่งแวดล้อม,47,47,-,46,31,...,-,16,4,1,-,6,1,-,-,4
1875,66,4 เฉลิมพระเกียรติ จังหวัดสกลนคร,สาธารณสุขศาสตร์,None,สาธารณสุขศาสตรบัณฑิต,179,179,-,177,86,...,1,93,29,6,2,33,-,-,2,21
1876,66,4 เฉลิมพระเกียรติ จังหวัดสกลนคร,วิทยาลัยการชลประทาน,None,วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมโยธา-ชลประทาน,72,72,-,68,59,...,-,13,6,-,3,3,-,1,-,-